Add pretty-printed star count and download count numbers
duckdb/community-extensions pull request #163
Opened 2024-10-23 14:29 UTC by szarnyasg

I added pretty-printed fields to the Markdown generator, with the rationale being that it's a bit more convenient to do it here than to do it from Jekyll/Liquid.

2024-10-23 14:43 UTC, carlopi commented
```sql
CREATE MACRO pretty_number(x) AS (
    CASE
      WHEN x < 1000 THEN x || ''
      WHEN x < 1000000 THEN ((x/1000)::DECIMAL(10,1)) || 'K'
      ELSE 'a lot'
    END);
```
The need for this macro in DuckDB is closer and closer

2024-10-23 14:57 UTC, carlopi approved these changes
Thanks!

2024-10-23 15:05 UTC, carlopi commented
(bash script do not really makes sense, but will fix it while rebasing)

2024-10-23 15:17 UTC, carlopi commented
Moving to draft, this will not properly work if the either stars of download numbers are empty / null. I can fix it later.

2024-10-24 11:55 UTC, szarnyasg commented
@carlopi I fixed the issue and improved the ergonomics of the scripts. PTAL.

2024-10-24 12:05 UTC, carlopi requested changes

2024-10-24 12:05 UTC, carlopi commented on scripts/generate_md.sh
> +       DOWNLOAD_COUNT=$(cat downloads-last-week.json | jq ".${extension}")
```suggestion
       DOWNLOAD_COUNT=$(cat build/downloads-last-week.json | jq ".${extension}")
```

2024-10-24 12:05 UTC, carlopi commented on scripts/generate_md.sh
> +       cat build/downloads-last-week.json | jq ".$extension" >> $EXTENSION_README
```suggestion
```

2024-10-24 12:05 UTC, carlopi approved these changes

2024-10-24 12:06 UTC, merged

2024-10-24 12:09 UTC, carlopi commented
Looks great, thanks!

Updating the markdowns is blocked on extensions downloads numbers being emtpy...